### ISSUE TITLE
DatabaseSchema Review

### ISSUE THREAD

**Issue by BCrawfordScott** [davezig/favorEats#3]
Really great work team, the schema makes sense  to me. Just a couple notes:

- [x] Add createdAt/updatedAt to all tables
- Locations: it might not be necessary to create a whole table unless you anticipate more than one restaurant having the same location.  If no location will ever be shared, it could be fair to save all that information on the restaurants table.  This is totally your call - either way will work just fine.  Please organize in whatever way feels good to you.

Looking forward to seeing more!

**Comment by laurenchambers** [comment]
Added createdAt/updatedAt to all tables.
Removed the 'locations' table and added these properties tot he Restaurant table: streetAddress, city, state, zipCode
